name: Renew NoIP hostname

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  renew:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Chromium and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          which chromium-browser
          which chromedriver
          chromedriver --version      

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install selenium pyotp requests

      - name: Run noip-renew.py
        env:
          NOIP_USERNAME: ${{ secrets.NOIP_USERNAME }}
          NOIP_PASSWORD: ${{ secrets.NOIP_PASSWORD }}
          NOIP_2FA_SECRET_KEY: ${{ secrets.NOIP_2FA_SECRET_KEY }}
        run: |
          ENCODED_PASSWORD=$(echo -n "$NOIP_PASSWORD" | base64)
          python noip-renew.py "$NOIP_USERNAME" "$ENCODED_PASSWORD" "$NOIP_2FA_SECRET_KEY" 2

      - name: Upload 2FA debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 2fa_debug_files
          path: |
            page_2fa_debug.html
            2fa_debug.png
          if-no-files-found: ignore
